import type { TourDefinition } from "../../core/TourTypes";

export const editorActivationTour: TourDefinition = {
  id: "editor-activation",
  version: 1,
  title: "You are ready. Learn LatexDo by using it.",
  intro:
    "Spend two minutes trying the workflow: select, ask, add context, cite, check, compile, and navigate.",
  steps: [
    {
      id: "select-ai",
      featureId: "ai-reformulation",
      targetId: "editor",
      title: "AI lives inside your editor",
      body: "Select the first sentence in the tutorial document. When text is selected, LatexDo exposes AI actions for that exact passage.",
      mode: "user-action",
      cta: "I selected text",
      expectedEvent: "editor:selection-created",
      success: "Selection detected. You can now ask AI to work on only that text.",
      fallback: "Drag across a sentence in the source editor.",
    },
    {
      id: "ask-ai-selection",
      featureId: "ask-ai-selection",
      targetId: "ai-sidebar",
      title: "Ask AI about your writing",
      body: "Use Ask AI about Selection to attach the selected passage to the chat. This avoids copy and paste and keeps the file/line context.",
      mode: "user-action",
      cta: "Attach selection",
      expectedEvent: "ai:selection-attached",
      success: "AI now knows exactly what passage you mean.",
      fallback: "Use the editor context menu or shortcut for Ask AI about Selection.",
    },
    {
      id: "file-context",
      featureId: "ai-file-context",
      targetId: "ai-composer",
      title: "Type @ to bring project context",
      body: "Click the AI composer and type @. The real project-file picker appears, so AI can reason with files instead of vague prompts.",
      mode: "user-action",
      cta: "Attach a file",
      expectedEvent: "ai:file-context-attached",
      success: "Project context attached.",
      fallback: "Open the AI panel, type @, then choose a file suggestion.",
    },
    {
      id: "citation",
      featureId: "citations",
      targetId: "citation",
      title: "A scientific claim needs evidence",
      body: "Use the citation action near the claim. LatexDo adapts citation insertion to your document context.",
      mode: "user-action",
      cta: "Insert citation",
      expectedEvent: "citation:inserted",
      success: "Citation behavior discovered.",
      fallback: "Use the Cite button in the editor toolbar.",
    },
    {
      id: "compile",
      featureId: "compile",
      targetId: "compile",
      title: "Your source and paper live together",
      body: "Compile with the toolbar button or Ctrl/Cmd + Enter. The tour completes this step only after a successful build.",
      mode: "user-action",
      cta: "Compile",
      expectedEvent: "compile:succeeded",
      success: "Your PDF is ready.",
      fallback:
        "If this tutorial document is not in a real project, skip this step and try compile in your project.",
    },
    {
      id: "pdf-navigation",
      featureId: "synctex",
      targetId: "pdf-preview",
      title: "Jump between PDF and source",
      body: "Click in the generated PDF or use the source/PDF navigation buttons. LatexDo can move between what readers see and what you wrote.",
      mode: "user-action",
      cta: "Navigate PDF",
      expectedEvent: "synctex:navigated",
      success: "PDF/source navigation discovered.",
      fallback: "Compile first, then click inside the PDF preview.",
    },
    {
      id: "formatting",
      featureId: "formatting",
      targetId: "formatting",
      title: "Do not waste research time cleaning markup",
      body: "Use the table formatter or document formatter. LatexDo flashes the changed source instead of making formatting a chore.",
      mode: "user-action",
      cta: "Format",
      expectedEvent: "format:applied",
      success: "Formatting workflow discovered.",
      fallback:
        "Place the cursor in the small table and press the table-format button.",
    },
    {
      id: "problems",
      featureId: "problems",
      targetId: "problems",
      title: "LatexDo watches the document while you work",
      body: "Open Problems to inspect diagnostics and jump from an issue back to the corresponding source location.",
      mode: "user-action",
      cta: "Open Problems",
      expectedEvent: "problems:opened",
      success: "Problem-to-source workflow discovered.",
      fallback: "Use the warning icon in the top toolbar or the bottom panel tab.",
    },
    {
      id: "workspace",
      featureId: "workspace-map",
      targetId: "workspace",
      title: "This is your research workspace",
      body: "Explorer, editor, AI, PDF preview, Problems, history, search, and source control all orbit the same writing workflow.",
      mode: "explain",
      cta: "Start working",
      success:
        "You just learned: Select → AI, @ → context, Cite → references, Compile → PDF, PDF → source, Check → problems.",
    },
  ],
};
