// Detached helpers outlive the old application. Only the relaunched app confirms success.
export const macUpdateHelper = [
  "#!/bin/sh",
  "set -eu",
  'log_file="${LATEXDO_UPDATE_LOG:?}"',
  'mkdir -p "$(dirname "$log_file")"',
  'exec >>"$log_file" 2>&1',
  'expected="${LATEXDO_UPDATE_EXPECTED_VERSION:?}"',
  'receipt="$(dirname "$0")/version-receipt"',
  'probe_pid=""',
  "wait_for_exit() {",
  "  remaining=300",
  '  while kill -0 "${LATEXDO_UPDATE_APP_PID:?}" 2>/dev/null; do',
  "    remaining=$((remaining - 1))",
  '    [ "$remaining" -gt 0 ] || return 1',
  "    sleep 0.2",
  "  done",
  "}",
  "verify_application() {",
  '  rm -f "$receipt"',
  '  "$1" --latexdo-verify-update "$expected" "$receipt" &',
  "  probe_pid=$!",
  "  remaining=150",
  '  while kill -0 "$probe_pid" 2>/dev/null; do',
  "    remaining=$((remaining - 1))",
  '    if [ "$remaining" -eq 0 ]; then',
  '      kill "$probe_pid" 2>/dev/null || true',
  "      return 1",
  "    fi",
  "    sleep 0.2",
  "  done",
  '  wait "$probe_pid" || return 1',
  '  probe_pid=""',
  '  [ -f "$receipt" ] && [ "$(cat "$receipt")" = "$expected" ]',
  "}",
  'target_app="${LATEXDO_UPDATE_TARGET_APP:?}"',
  'target_dir="$(dirname "$target_app")"',
  'target_name="$(basename "$target_app")"',
  'staged_app="$target_dir/.$target_name.update.$$"',
  'backup_app="$target_dir/.$target_name.previous.$$"',
  'mount_dir=""',
  "finish() {",
  "  status=$?",
  "  trap - EXIT",
  '  if [ -n "$probe_pid" ]; then kill "$probe_pid" 2>/dev/null || true; fi',
  '  if [ "$status" -ne 0 ]; then',
  '    echo "Update failed: application replacement or version verification failed. See $log_file" > "${LATEXDO_UPDATE_FAILURE_FILE:?}"',
  '    if [ -d "$backup_app" ]; then',
  '      rm -rf "$target_app"',
  '      mv "$backup_app" "$target_app" || exit 1',
  "    fi",
  '    if ! kill -0 "${LATEXDO_UPDATE_APP_PID:?}" 2>/dev/null; then',
  '      open -n "$target_app" || true',
  "    fi",
  "  fi",
  '  if [ -n "$mount_dir" ]; then',
  '    hdiutil detach "$mount_dir" -quiet || true',
  '    rmdir "$mount_dir" || true',
  "  fi",
  '  rm -rf "$staged_app" "$(dirname "$0")"',
  '  exit "$status"',
  "}",
  "trap finish EXIT",
  "wait_for_exit",
  'mount_dir="$(mktemp -d "${TMPDIR:-/tmp}/latexdo-update-mount.XXXXXX")"',
  'hdiutil attach "${LATEXDO_UPDATE_DMG:?}" -nobrowse -readonly -mountpoint "$mount_dir"',
  'source_app="$(find "$mount_dir" -maxdepth 1 -type d -name \'*.app\' -print -quit)"',
  '[ -n "$source_app" ] || exit 1',
  'ditto "$source_app" "$staged_app"',
  '[ -x "$staged_app/Contents/MacOS/${LATEXDO_UPDATE_EXECUTABLE_NAME:?}" ] || exit 1',
  'staged_version="$(/usr/libexec/PlistBuddy -c \'Print :CFBundleShortVersionString\' "$staged_app/Contents/Info.plist")"',
  '[ "$staged_version" = "$expected" ] || exit 1',
  'mv "$target_app" "$backup_app"',
  'mv "$staged_app" "$target_app"',
  'verify_application "$target_app/Contents/MacOS/${LATEXDO_UPDATE_EXECUTABLE_NAME:?}"',
  'echo "Verified installed application $target_app version $expected"',
  'open -n "$target_app"',
  'rm -rf "$backup_app" || true',
  'echo "Replacement verified; waiting for the relaunched application to confirm the update."',
].join("\n");

export const linuxUpdateHelper = [
  "#!/bin/sh",
  "set -eu",
  'log_file="${LATEXDO_UPDATE_LOG:?}"',
  'mkdir -p "$(dirname "$log_file")"',
  'exec >>"$log_file" 2>&1',
  'expected="${LATEXDO_UPDATE_EXPECTED_VERSION:?}"',
  'receipt="$(dirname "$0")/version-receipt"',
  'probe_pid=""',
  "wait_for_exit() {",
  "  remaining=300",
  '  while kill -0 "${LATEXDO_UPDATE_APP_PID:?}" 2>/dev/null; do',
  "    remaining=$((remaining - 1))",
  '    [ "$remaining" -gt 0 ] || return 1',
  "    sleep 0.2",
  "  done",
  "}",
  "verify_application() {",
  '  rm -f "$receipt"',
  '  "$1" --latexdo-verify-update "$expected" "$receipt" &',
  "  probe_pid=$!",
  "  remaining=150",
  '  while kill -0 "$probe_pid" 2>/dev/null; do',
  "    remaining=$((remaining - 1))",
  '    if [ "$remaining" -eq 0 ]; then',
  '      kill "$probe_pid" 2>/dev/null || true',
  "      return 1",
  "    fi",
  "    sleep 0.2",
  "  done",
  '  wait "$probe_pid" || return 1',
  '  probe_pid=""',
  '  [ -f "$receipt" ] && [ "$(cat "$receipt")" = "$expected" ]',
  "}",
  'target="${LATEXDO_UPDATE_TARGET_APPIMAGE:?}"',
  'replacement="${LATEXDO_UPDATE_APPIMAGE:?}"',
  'target_name="$(basename "$target")"',
  'target_dir="$(dirname "$target")"',
  'staged="$target_dir/.$target_name.update.$$"',
  'backup="$target_dir/.$target_name.previous.$$"',
  "finish() {",
  "  status=$?",
  "  trap - EXIT",
  '  if [ -n "$probe_pid" ]; then kill "$probe_pid" 2>/dev/null || true; fi',
  '  if [ "$status" -ne 0 ]; then',
  '    echo "Update failed: AppImage replacement or version verification failed. See $log_file" > "${LATEXDO_UPDATE_FAILURE_FILE:?}"',
  '    if [ -f "$backup" ]; then',
  '      rm -f "$target"',
  '      mv "$backup" "$target" || exit 1',
  "    fi",
  '    if [ -x "$target" ] && ! kill -0 "${LATEXDO_UPDATE_APP_PID:?}" 2>/dev/null; then',
  '      "$target" >/dev/null 2>&1 &',
  "    fi",
  "  fi",
  '  rm -f "$staged"',
  '  rm -rf "$(dirname "$0")"',
  '  exit "$status"',
  "}",
  "trap finish EXIT",
  "wait_for_exit",
  'cp "$replacement" "$staged"',
  'chmod +x "$staged"',
  'mv "$target" "$backup"',
  'mv "$staged" "$target"',
  'verify_application "$target"',
  'echo "Verified installed application $target version $expected"',
  '"$target" >/dev/null 2>&1 &',
  'rm -f "$backup" "$replacement" || true',
  'echo "Replacement verified; waiting for the relaunched application to confirm the update."',
].join("\n");

export const windowsUpdateHelper = [
  "$ErrorActionPreference = 'Stop'",
  "$logFile = $env:LATEXDO_UPDATE_LOG",
  "New-Item -ItemType Directory -Force -Path (Split-Path -Parent $logFile) | Out-Null",
  "function Write-Log {",
  "  param([string]$Message)",
  '  Add-Content -LiteralPath $logFile -Value ("[{0:u}] {1}" -f (Get-Date), $Message)',
  "}",
  "function Test-LatexDoVersionMatch {",
  "  param([string]$Installed, [string]$Expected)",
  "  function Get-VersionParts {",
  "    param([string]$Value)",
  "    $normalized = $Value.Trim()",
  "    if ($normalized -match '^[vV]') { $normalized = $normalized.Substring(1) }",
  "    $hyphenIndex = $normalized.IndexOf('-')",
  "    if ($hyphenIndex -ge 0) {",
  "      $coreText = $normalized.Substring(0, $hyphenIndex)",
  "      $prereleaseText = $normalized.Substring($hyphenIndex + 1)",
  "    } else {",
  "      $coreText = $normalized",
  "      $prereleaseText = ''",
  "    }",
  "    $prerelease = @()",
  "    if ($prereleaseText -ne '') {",
  "      $prerelease = @($prereleaseText -split '[.-]' | Where-Object { $_ -ne '' })",
  "    }",
  "    return @{ Core = @($coreText -split '\\.' | Where-Object { $_ -ne '' }); Prerelease = @($prerelease) }",
  "  }",
  "  function Compare-VersionPart {",
  "    param([string]$Left, [string]$Right)",
  "    $leftLong = 0L",
  "    $rightLong = 0L",
  "    $leftNumeric = [long]::TryParse($Left, [ref]$leftLong)",
  "    $rightNumeric = [long]::TryParse($Right, [ref]$rightLong)",
  "    if ($leftNumeric -and $rightNumeric) {",
  "      if ($leftLong -eq $rightLong) { return 0 }",
  "      if ($leftLong -gt $rightLong) { return 1 }",
  "      return -1",
  "    }",
  "    if ($Left -eq $Right) { return 0 }",
  "    if ($Left -gt $Right) { return 1 }",
  "    return -1",
  "  }",
  "  $installedParts = Get-VersionParts -Value $Installed",
  "  $expectedParts = Get-VersionParts -Value $Expected",
  "  $coreLength = [Math]::Max($installedParts.Core.Count, $expectedParts.Core.Count)",
  "  for ($index = 0; $index -lt $coreLength; $index += 1) {",
  "    $leftPart = if ($index -lt $installedParts.Core.Count) { $installedParts.Core[$index] } else { '0' }",
  "    $rightPart = if ($index -lt $expectedParts.Core.Count) { $expectedParts.Core[$index] } else { '0' }",
  "    if ((Compare-VersionPart -Left $leftPart -Right $rightPart) -ne 0) { return $false }",
  "  }",
  "  if ($installedParts.Prerelease.Count -eq 0 -or $expectedParts.Prerelease.Count -eq 0) {",
  "    return $installedParts.Prerelease.Count -eq $expectedParts.Prerelease.Count",
  "  }",
  "  $prereleaseLength = [Math]::Max($installedParts.Prerelease.Count, $expectedParts.Prerelease.Count)",
  "  for ($preIndex = 0; $preIndex -lt $prereleaseLength; $preIndex += 1) {",
  "    if ($preIndex -ge $installedParts.Prerelease.Count) { return $false }",
  "    if ($preIndex -ge $expectedParts.Prerelease.Count) { return $false }",
  "    if ((Compare-VersionPart -Left $installedParts.Prerelease[$preIndex] -Right $expectedParts.Prerelease[$preIndex]) -ne 0) { return $false }",
  "  }",
  "  return $true",
  "}",
  "$helperRoot = $PSScriptRoot",
  "try {",
  "  Write-Log 'Starting Windows update helper'",
  '  Write-Log ("CurrentProcess={0}" -f $PID)',
  '  Write-Log ("ExpectedVersion={0}" -f $env:LATEXDO_UPDATE_EXPECTED_VERSION)',
  '  Write-Log ("Installer={0}" -f $env:LATEXDO_UPDATE_INSTALLER)',
  '  Write-Log ("TargetExe={0}" -f $env:LATEXDO_UPDATE_TARGET_EXE)',
  "  $expectedVersion = $env:LATEXDO_UPDATE_EXPECTED_VERSION",
  "  if (-not $expectedVersion) {",
  '    throw "Expected update version was not provided (LATEXDO_UPDATE_EXPECTED_VERSION)."',
  "  }",
  "  $appPid = [int]$env:LATEXDO_UPDATE_APP_PID",
  '  Write-Log ("Waiting for PID {0}" -f $appPid)',
  "  if (Get-Process -Id $appPid -ErrorAction SilentlyContinue) { Wait-Process -Id $appPid -Timeout 60 -ErrorAction Stop }",
  "  $installer = $env:LATEXDO_UPDATE_INSTALLER",
  "  $targetExe = $env:LATEXDO_UPDATE_TARGET_EXE",
  "  if (-not (Test-Path -LiteralPath $installer)) {",
  '    throw "Installer is missing: $installer"',
  "  }",
  "  $installStartedAt = Get-Date",
  "  $targetDirectory = Split-Path -Parent $targetExe",
  '  $installerArgs = "/S /D=$targetDirectory"',
  "  $process = Start-Process -FilePath $installer -ArgumentList $installerArgs -Wait -PassThru",
  '  Write-Log ("InstallStart={0:u}" -f $installStartedAt)',
  '  Write-Log ("InstallFinish={0:u}" -f (Get-Date))',
  '  Write-Log ("InstallerExitCode={0}" -f $process.ExitCode)',
  "  if ($process.ExitCode -ne 0) {",
  '    throw "Installer exited with code $($process.ExitCode)"',
  "  }",
  "  if (-not (Test-Path -LiteralPath $targetExe)) {",
  '    throw "Installed executable was not found: $targetExe"',
  "  }",
  "  $item = Get-Item -LiteralPath $targetExe",
  "  $installedVersion = $item.VersionInfo.ProductVersion",
  "  $installedFileVersion = $item.VersionInfo.FileVersion",
  '  Write-Log ("TargetProductVersion={0}" -f $installedVersion)',
  '  Write-Log ("TargetFileVersion={0}" -f $installedFileVersion)',
  "  if (-not $installedVersion) {",
  '    throw "Could not determine installed executable version."',
  "  }",
  "  $versionMatches = Test-LatexDoVersionMatch -Installed $installedVersion -Expected $expectedVersion",
  '  Write-Log ("VersionMatch={0} ExpectedVersion={1} InstalledVersion={2}" -f $versionMatches, $expectedVersion, $installedVersion)',
  "  if (-not $versionMatches) {",
  '    throw "Installed executable ProductVersion $installedVersion does not match expected update version $expectedVersion."',
  "  }",
  "  $receipt = Join-Path $helperRoot 'version-receipt'",
  '  $probeArgs = \'--latexdo-verify-update "{0}" "{1}"\' -f $expectedVersion, $receipt',
  "  $probe = Start-Process -FilePath $targetExe -ArgumentList $probeArgs -PassThru",
  "  if (-not $probe.WaitForExit(30000)) {",
  "    Stop-Process -Id $probe.Id -Force -ErrorAction SilentlyContinue",
  "    throw 'Installed application version probe timed out.'",
  "  }",
  "  if ($probe.ExitCode -ne 0 -or -not (Test-Path -LiteralPath $receipt)) {",
  "    throw 'Installed application did not confirm its packaged version.'",
  "  }",
  "  if ((Get-Content -LiteralPath $receipt -Raw) -ne $expectedVersion) {",
  "    throw 'Installed application version receipt does not match.'",
  "  }",
  '  Write-Log ("Verification=PASS ExpectedVersion={0} InstalledVersion={1}" -f $expectedVersion, $installedVersion)',
  "  $relaunched = Start-Process -FilePath $targetExe -PassThru",
  '  Write-Log ("RelaunchedPid={0}" -f $relaunched.Id)',
  '  Write-Log ("Verified and launched LatexDo {0}" -f $installedVersion)',
  "  Write-Log 'Windows update helper finished'",
  "} catch {",
  '  Set-Content -LiteralPath $env:LATEXDO_UPDATE_FAILURE_FILE -Value ("Update failed: {0}" -f $_.Exception.Message) -Encoding UTF8',
  '  Write-Log ("Verification=FAIL Reason={0}" -f $_.Exception.Message)',
  '  Write-Log ("Windows update helper failed: {0}" -f $_.Exception.Message)',
  "  try {",
  "    if (Test-Path -LiteralPath $env:LATEXDO_UPDATE_TARGET_EXE) { Start-Process -FilePath $env:LATEXDO_UPDATE_TARGET_EXE }",
  "  } catch {",
  '    Write-Log ("Could not reopen application after failure: {0}" -f $_.Exception.Message)',
  "  }",
  "  exit 1",
  "} finally {",
  "  Start-Sleep -Seconds 2",
  "  Remove-Item -LiteralPath $helperRoot -Recurse -Force -ErrorAction SilentlyContinue",
  "}",
  "",
].join("\r\n");
