import { beforeEach, describe, expect, it, vi } from "vitest";
import { generateStep } from "../ai/aiClient";
import { defaultAiConfig, type AiConfig } from "../ai/aiConfig";
import {
  LlmTranscriptCleanup,
  buildCleanupMessages,
  cleanupFailureError,
  createTranscriptCleanup,
} from "./transcriptCleanup";

vi.mock("../ai/aiClient", () => ({
  generateStep: vi.fn(),
}));

describe("transcriptCleanup", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("bans aggressive rewriting in the cleanup policy", () => {
    const messages = buildCleanupMessages(
      "so the result is basically the same but we need to change lambda",
    );
    const system = messages.find((m) => m.role === "system")?.content ?? "";
    const user = messages.find((m) => m.role === "user")?.content ?? "";

    expect(system).toContain("Preserve the speaker's wording, meaning,");
    for (const prohibition of [
      "Do not summarize.",
      "Do not rewrite.",
      "Do not improve style.",
      "Do not make the writing more professional.",
      "Do not add information.",
      "Do not remove information.",
      "Do not replace the user's vocabulary with synonyms.",
      "Return only the cleaned transcript.",
      "escape special characters such as $, %, &, #, _, {, }, ~, and ^",
    ]) {
      expect(system).toContain(prohibition);
    }
    // The raw wording is handed to the model verbatim for a conservative pass.
    expect(user).toContain("so the result is basically the same");
    expect(user).toContain("lambda");
  });

  it("runs cleanup through the existing provider stack at temperature 0", async () => {
    vi.mocked(generateStep).mockResolvedValueOnce({
      type: "text",
      content: "So the result is basically the same, but we need to change lambda.",
    });
    const cleanup = new LlmTranscriptCleanup(cloudConfig());
    const cleaned = await cleanup.cleanup(
      "so the result is basically the same but we need to change lambda",
    );

    expect(cleaned).toContain("basically");
    expect(cleaned).toContain("lambda");
    expect(generateStep).toHaveBeenCalledTimes(1);
    const req = vi.mocked(generateStep).mock.calls[0][0] as {
      provider: string;
      options: { temperature?: number };
    };
    expect(req.provider).toBe("cloud");
    expect(req.options.temperature).toBe(0);
  });

  it("fails without changing the vocabulary in the request", async () => {
    // Regression guard: the message payload for cleanup must contain exactly
    // the user's words, not a paraphrase generated by the app.
    vi.mocked(generateStep).mockResolvedValueOnce({ type: "text", content: "x" });
    const cleanup = new LlmTranscriptCleanup(cloudConfig());
    await cleanup.cleanup("we need to change the introduction");
    const messages = vi.mocked(generateStep).mock.calls[0][0] as {
      messages: { role: string; content: string }[];
    };
    const user = messages.messages.find((m) => m.role === "user")?.content ?? "";
    expect(user).toBe("Transcript:\nwe need to change the introduction");
  });

  it("returns null when AI is switched off", () => {
    expect(
      createTranscriptCleanup({ ...defaultAiConfig, provider: "off" }),
    ).toBeNull();
  });

  it("wraps provider errors so dictation can fall back to the raw transcript", async () => {
    vi.mocked(generateStep).mockResolvedValueOnce({
      type: "error",
      content: "Provider blew up",
    });
    const cleanup = new LlmTranscriptCleanup(cloudConfig());
    await expect(cleanup.cleanup("some words")).rejects.toMatchObject({
      code: "cleanup-failed",
    });
    expect(cleanupFailureError("x")).toMatchObject({ code: "cleanup-failed" });
  });
});

function cloudConfig(): AiConfig {
  return {
    ...defaultAiConfig,
    provider: "cloud",
    selection: {
      mode: "custom",
      custom: {
        kind: "cloud",
        providerId: "openai",
        model: "gpt-4o-mini",
        baseUrl: "",
        credentialId: "credential-openai-primary",
      },
    },
    cloud: {
      providerId: "openai",
      vendor: "openai",
      model: "gpt-4o-mini",
      baseUrl: "",
      credentialId: "credential-openai-primary",
      credentialConfigured: true,
    },
  };
}