import { act,cleanup,fireEvent,render,screen } from "@testing-library/react";
import { afterEach,beforeEach,describe,it,expect,vi } from "vitest";
import { TourOverlay } from "./TourOverlay";
import { emitProductEvent } from "../core/ProductEvents";
import { getTourProgress,loadDiscoveryStore,updateTourProgress } from "../core/DiscoveryStore";
import type { TourDefinition } from "../core/TourTypes";
const tour:TourDefinition={id:"coverage-tour",version:1,title:"Try the editor",intro:"Learn the workflow",steps:[{id:"compile",featureId:"compile",targetId:"compile",title:"Build a PDF",body:"Compile the paper",mode:"user-action",cta:"I clicked compile",expectedEvent:"compile:succeeded",success:"PDF ready",fallback:"Use the compile button"},{id:"finish",featureId:"finish",targetId:"missing-target",title:"Keep writing",body:"Tour complete",mode:"explain",cta:"Finish",success:"Ready"}]};
beforeEach(()=>{vi.useFakeTimers();localStorage.clear();});
afterEach(()=>{cleanup();vi.useRealTimers();vi.restoreAllMocks();});
function setup(){const onPrepare=vi.fn(),onRestore=vi.fn();const view=render(<><button data-tour-id="compile">Compile target</button><TourOverlay tour={tour} launchNonce={1} onPrepare={onPrepare} onRestore={onRestore}/></>);act(()=>vi.advanceTimersByTime(650));return {...view,onPrepare,onRestore};}
function start(){fireEvent.click(screen.getByRole("button",{name:"Start interactive tour"}));act(()=>vi.advanceTimersByTime(80));}
describe("interactive onboarding tour",()=>{
  it("prepares a workspace, waits for the expected event, and restores it on completion",()=>{const view=setup();vi.spyOn(screen.getByText("Compile target"),"getBoundingClientRect").mockReturnValue({top:20,left:30,width:100,height:40} as DOMRect);start();expect(view.onPrepare).toHaveBeenCalledOnce();expect(view.container.querySelector(".tour-spotlight")).toHaveStyle({top:"12px",left:"22px",width:"116px",height:"56px"});fireEvent.resize(window);fireEvent.scroll(window);fireEvent.click(screen.getByRole("button",{name:"I clicked compile"}));expect(screen.getByRole("status")).toHaveTextContent("complete the action");act(()=>emitProductEvent({type:"compile:failed"}));expect(getTourProgress(tour.id,1).completedSteps).toEqual([]);act(()=>emitProductEvent({type:"compile:succeeded"}));expect(screen.getByRole("status")).toHaveTextContent("PDF ready");expect(loadDiscoveryStore().features.compile.state).toBe("mastered");act(()=>vi.advanceTimersByTime(650));expect(screen.getByRole("heading",{name:"Keep writing"})).toBeInTheDocument();expect(view.container.querySelector(".tour-spotlight")).toBeNull();fireEvent.click(screen.getByRole("button",{name:"Finish"}));act(()=>vi.advanceTimersByTime(650));expect(getTourProgress(tour.id,1)).toMatchObject({state:"completed",completedSteps:["compile","finish"]});expect(view.onRestore).toHaveBeenCalledOnce();expect(screen.queryByRole("dialog")).not.toBeInTheDocument();});
  it("allows demonstrations and skipped steps without marking them mastered",()=>{const view=setup();start();fireEvent.click(screen.getByRole("button",{name:"Show me"}));expect(loadDiscoveryStore().features.compile.state).toBe("tried");act(()=>vi.advanceTimersByTime(650));fireEvent.click(screen.getByRole("button",{name:"Skip step"}));expect(getTourProgress(tour.id,1).skippedSteps).toEqual(["finish"]);act(()=>vi.advanceTimersByTime(180));expect(view.onRestore).toHaveBeenCalledOnce();});
  it.each([false,true])("dismisses the tour after starting=%s",started=>{const view=setup();if(started)start();fireEvent.click(screen.getByRole("button",{name:started?"Skip tour":"Skip for now"}));expect(getTourProgress(tour.id,1).state).toBe("dismissed");expect(view.onRestore).toHaveBeenCalledOnce();expect(loadDiscoveryStore().analytics.at(-1)?.type).toBe("tour_dismissed");});
  it.each(["completed","dismissed"] as const)("does not relaunch a %s tour",state=>{updateTourProgress({...getTourProgress(tour.id,1),state});setup();expect(screen.queryByRole("dialog")).not.toBeInTheDocument();});
});
